---
abstract: 'Yet another INI reader/writer (round trip, includes, variables, nest)'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  Module::Build: 0.3601
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200007, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Config-Ini-OnDrugs
requires:
  Exporter::Lite: 0
  File::Slurp: 0
  File::chdir: 0
  Package::Alias: 0
  Sub::Spec: 1.0.4
  Test::More: 0.96
  perl: 5.010000
resources:
  homepage: http://search.cpan.org/dist/Config-Ini-OnDrugs/
  repository: http://github.com/sharyanto/perl-Config-Ini-OnDrugs
version: 0.08
